### ISSUE TITLE
Feature: Pinning rooms to the top of the list

### ISSUE THREAD

**Issue by WyattHBrown** [Kalissaac/Eigen#10]
Similar to what element used to do before they changed it, **it would be nice to pin/favourite rooms at the top of the sidebar** (or put them in their own category) even if they have no new messages. It would be useful for groups you might frequent, or for people who are in a lot of rooms.

**Comment by dnisbetjones** [comment]
Also see #5

**Comment by WyattHBrown** [comment]
Ah well then

**Comment by WyattHBrown** [comment]
I didn’t see that one when looking at the others
