### ISSUE TITLE
Room events are incorrect

### ISSUE THREAD

**Issue by dnisbetjones** [Kalissaac/Eigen#17]
Room events such as kick/ban, message removals or name and avatar changes are incorrect.

A user being banned shows the mod/admin as being banned instead:
![Screenshot 2023-04-12 at 19 54 18](https://user-images.githubusercontent.com/64179257/231636211-ff48aec1-42ce-4d52-ad1a-c71a6208069c.jpg)

![Screenshot 2023-04-12 at 19 51 25](https://user-images.githubusercontent.com/64179257/231635934-6b340ada-764f-48f7-8c5a-60f21f23f65e.jpg)

**Comment by kenrachynski** [comment]
<img width="423" alt="image" src="https://github.com/Kalissaac/Eigen/assets/867597/d27263bf-e15f-4f0c-b858-c8a14b0aa8b0">
