### ISSUE TITLE
Feature: sorting rooms

### ISSUE THREAD

**Issue by kenrachynski** [Kalissaac/Eigen#2]
I would love to have the option to sort Rooms by alphanumerics in addition to activity. 

I'm one of those who looks for conversations based on their position on the screen. So having Rooms move when activity changes inside of them is problematic for me.

I do see that after activity (highlights, unread messages), you are sorting by alphanumeric name. I'm not sure whether I really like lowercase letters being sorted after uppercase, but as long as they just don't move, I can put up with either.

**Comment by Kalissaac** [comment]
Thanks for opening this issue! I definitely agree that the room organization could do with some improvements. I'll add the option to sort alphanumerically, ignoring activity indicators. I want to also explore the option to manually sort rooms, but I'm not totally sure if SwiftUI supports that.
