### ISSUE TITLE
Bug: User avatars in rooms don't populate or 'stick'

### ISSUE THREAD

**Issue by dnisbetjones** [Kalissaac/Eigen#7]
New and existing messages won't populate with a user avatar unless you scroll up to refresh them. In addition, they don't 'stick' when switching rooms.

Video:

https://user-images.githubusercontent.com/64179257/218278791-c6f5dad2-976c-49a1-9976-d7786064fbb0.mp4

**Comment by Kalissaac** [comment]
Thanks for this, I actually fixed it in 7089ad43ef8c9c2a6ee758a04063fff65ddcc0b8 but haven't made a release yet
If you want to try that build, you can download it from here: https://github.com/Kalissaac/Eigen/suites/10860872664/artifacts/547600537
