### ISSUE TITLE
Bug: Input field focus

### ISSUE THREAD

**Issue by kenrachynski** [Kalissaac/Eigen#9]
I've been noticing that the input field doesn't always remain in focus. On doing some research on how to enforce this, I realized that your code is attempting to do so. I haven't gone deep into the debugger yet to see if I can figure out why so I'm leaving an issue here before I forget about it.

Steps to reproduce:
* in a room of your choice, enter some text and send it or not. the input field is still selected
* select a new room. notice that the input field is selected
* select your original room. the input field is no longer selected
* select a third room. the input field is selected
* select your original room. the input field is no longer selected

This behaviour appears to apply to People as well.

**Comment by Kalissaac** [comment]
Yeah the currently solution is pretty janky because SwiftUI doesn't have a native way of making a TextField become first responder: https://stackoverflow.com/q/56507839
I'll try out some of the other solutions posted there to see if I can find one that will be more consistent

**Comment by kenrachynski** [comment]
I bumped into this one as well: https://stackoverflow.com/q/58311022

Interesting that Xcode 13+ is supposed to make the `focused` modifier usable and yet, here we are.

**Comment by Kalissaac** [comment]
I *think* this commit should fix it, I added a `task` to the TextField and also put a delay on the original trigger just in case it fails. From my testing it seemed to be pretty consistent, but if it still doesn't work for you please reopen and we'll figure out another solution.

**Comment by kenrachynski** [comment]
it did indeed fix it.
